ADDR_MODEL_NUMBER = 0
LEN_MODEL_NUMBER = 2

ADDR_MODEL_INFORMATION = 2
LEN_MODEL_INFORMATION = 4

ADDR_FIRMWARE_VERSION = 6
LEN_FIRMWARE_VERSION = 1

ADDR_ID = 7
LEN_ID = 1

ADDR_BAUD_RATE = 8
LEN_BAUD_RATE = 1

ADDR_RETURN_DELAY_TIME = 9
LEN_RETURN_DELAY_TIME = 1

ADDR_DRIVE_MODE = 10
LEN_DRIVE_MODE = 1

ADDR_OPERATING_MODE = 11
LEN_OPERATING_MODE = 1

ADDR_SECONDARY_ID = 12
LEN_SECONDARY_ID = 1

ADDR_PROTOCOL_VERSION = 13
LEN_PROTOCOL_VERSION = 1

ADDR_HOMING_OFFSET = 20
LEN_HOMING_OFFSET = 4

ADDR_MOVING_THRESHOLD = 24
LEN_MOVING_THRESHOLD = 4

ADDR_TEMPERATURE_LIMIT = 31
LEN_TEMPERATURE_LIMIT = 1

ADDR_MAX_VOLTAGE_LIMIT = 32
LEN_MAX_VOLTAGE_LIMIT = 2

ADDR_MIN_VOLTAGE_LIMIT = 34
LEN_MIN_VOLTAGE_LIMIT = 2

ADDR_PWM_LIMIT = 36
LEN_PWM_LIMIT = 2

ADDR_ACCELERATION_LIMIT = 40
LEN_ACCELERATION_LIMIT = 4

ADDR_VELOCITY_LIMIT = 44
LEN_VELOCITY_LIMIT = 4

ADDR_MAX_POSITION_LIMIT = 48
LEN_MAX_POSITION_LIMIT = 4

ADDR_MIN_POSITION_LIMIT = 52
LEN_MIN_POSITION_LIMIT = 4

ADDR_SHUTDOWN = 63
LEN_SHUTDOWN = 1

ADDR_TORQUE_ENABLE = 64
LEN_TORQUE_ENABLE = 1

ADDR_LED = 65
LEN_LED = 1

ADDR_STATUS_RETURN_LEVEL = 68
LEN_STATUS_RETURN_LEVEL = 1

ADDR_REGISTERED_INSTRUCTION = 69
LEN_REGISTERED_INSTRUCTION = 1

ADDR_HARDWARE_ERROR = 70
LEN_HARDWARE_ERROR = 1

ADDR_FEEDFORWARD_2ND_GAIN = 88
LEN_FEEDFORWARD_2ND_GAIN = 2

ADDR_VELOCITY_I_GAIN = 76
LEN_VELOCITY_I_GAIN = 2

ADDR_VELOCITY_P_GAIN = 78
LEN_VELOCITY_P_GAIN = 2

ADDR_POSITION_D_GAIN = 80
LEN_POSITION_D_GAIN = 2

ADDR_POSITION_I_GAIN = 82
LEN_POSITION_I_GAIN = 2

ADDR_POSITION_P_GAIN = 84
LEN_POSITION_P_GAIN = 2

ADDR_FEEDFORWARD_2ND_GAIN = 88
LEN_FEEDFORWARD_2ND_GAIN = 2

ADDR_FEEDFORWARD_1ST_GAIN = 90
LEN_FEEDFORWARD_1ST_GAIN = 2

ADDR_BUS_WATCHDOG = 98
LEN_BUS_WATCHDOG = 1

ADDR_GOAL_PWM = 100
LEN_GOAL_PWM = 2

ADDR_GOAL_VELOCITY = 104
LEN_GOAL_VELOCITY = 4

ADDR_PROFILE_ACCELERATION = 108
LEN_PROFILE_ACCELERATION = 4

ADDR_PROFILE_VELOCITY = 112
LEN_PROFILE_VELOCITY = 4

ADDR_GOAL_POSITION = 116
LEN_GOAL_POSITION = 4

ADDR_REALTIME_TICK = 120
LEN_REALTIME_TICK = 2

ADDR_MOVING = 122
LEN_MOVING = 1

ADDR_MOVING_STATUS = 123
LEN_MOVING_STATUS = 1

ADDR_PRESENT_PWM = 124
LEN_PRESENT_PWM = 2

ADDR_PRESENT_LOAD = 126
LEN_PRESENT_LOAD = 2

ADDR_PRESENT_VELOCITY = 128
LEN_PRESENT_VELOCITY = 4

ADDR_PRESENT_POSITION = 132
LEN_PRESENT_POSITION = 4

ADDR_VELOCITY_TRAJECTORY = 136
LEN_VELOCITY_TRAJECTORY = 4

ADDR_POSITION_TRAJECTORY = 140
LEN_POSITION_TRAJECTORY = 4

ADDR_PRESENT_INPUT_VOLTAGE = 144
LEN_PRESENT_INPUT_VOLTAGE = 2

ADDR_PRESENT_TEMPERATURE = 146
LEN_PRESENT_TEMPERATURE = 1

ADDR_INDIRECT_ADDRESS_1 = 168
LEN_INDIRECT_ADDRESS_1 = 2

ADDR_INDIRECT_ADDRESS_2 = 170
LEN_INDIRECT_ADDRESS_2 = 2

ADDR_INDIRECT_ADDRESS_3 = 172
LEN_INDIRECT_ADDRESS_3 = 2

ADDR_INDIRECT_ADDRESS_26 = 218
LEN_INDIRECT_ADDRESS_26 = 2

ADDR_INDIRECT_ADDRESS_27 = 220
LEN_INDIRECT_ADDRESS_27 = 2

ADDR_INDIRECT_ADDRESS_28 = 222
LEN_INDIRECT_ADDRESS_28 = 2

ADDR_INDIRECT_DATA_1 = 224
LEN_INDIRECT_DATA_1 = 1

ADDR_INDIRECT_DATA_2 = 225
LEN_INDIRECT_DATA_2 = 1

ADDR_INDIRECT_DATA_3 = 226
LEN_INDIRECT_DATA_3 = 1

ADDR_INDIRECT_DATA_26 = 249
LEN_INDIRECT_DATA_26 = 1

ADDR_INDIRECT_DATA_27 = 250
LEN_INDIRECT_DATA_27 = 1

ADDR_INDIRECT_DATA_28 = 251
LEN_INDIRECT_DATA_28 = 1

ADDR_INDIRECT_ADDRESS_29 = 578
LEN_INDIRECT_ADDRESS_29 = 2

ADDR_INDIRECT_ADDRESS_30 = 580
LEN_INDIRECT_ADDRESS_30 = 2

ADDR_INDIRECT_ADDRESS_31 = 582
LEN_INDIRECT_ADDRESS_31 = 2

ADDR_INDIRECT_ADDRESS_54 = 628
LEN_INDIRECT_ADDRESS_54 = 2

ADDR_INDIRECT_ADDRESS_55 = 630
LEN_INDIRECT_ADDRESS_55 = 2

ADDR_INDIRECT_ADDRESS_56 = 632
LEN_INDIRECT_ADDRESS_56 = 2

ADDR_INDIRECT_DATA_29 = 634
LEN_INDIRECT_DATA_29 = 1

ADDR_INDIRECT_DATA_30 = 635
LEN_INDIRECT_DATA_30 = 1

ADDR_INDIRECT_DATA_31 = 636
LEN_INDIRECT_DATA_31 = 1

ADDR_INDIRECT_DATA_54 = 659
LEN_INDIRECT_DATA_54 = 1

ADDR_INDIRECT_DATA_55 = 660
LEN_INDIRECT_DATA_55 = 1

ADDR_INDIRECT_DATA_56 = 661
LEN_INDIRECT_DATA_56 = 1
