import numpy as np
skel_file = "skel/double_walker3d_waist.skel"

BRICK_DOF = 6
CONTROL_BOUNDS = 1.5 * np.array([100]*15)

LEG_DOF = 6
RIGHT_IDX = 9
LEFT_IDX = 15
Q_DIM = 21
PITCH_IDX = 3
YAW_IDX = 4
ROLL_IDX = 5
X_IDX = 0

HIP_OFFSET = 0
HIP_OFFSET_TWIST = 1
HIP_OFFSET_LAT = 2
KNEE_OFFSET = 3
ANKLE_OFFSET = 4
ANKLE_OFFSET_LAT = 5

PELVIS_BODYNODE_IDX = 2
RIGHT_BODYNODE_IDX = 5
LEFT_BODYNODE_IDX = 8

# Same as 2D model, except L_PELVIS
L_PELVIS = 0.15
L_THIGH =    0.45
L_SHIN =   0.50
L_FOOT =   0.20
FOOT_RADIUS = 0.06

KP_GAIN = 300.0
KD_GAIN = 20.0

ALLOWED_COLLISION_IDS = [5,8] # The two feet
