BRICK_DOF = 6

LEG_DOF = 6
RIGHT_IDX = 9
LEFT_IDX = 15
Q_DIM = 21
THETA_IDX = 3
HIP_OFFSET = 0
HIP_OFFSET_LAT = 2
KNEE_OFFSET = 3
ANKLE_OFFSET = 4

PELVIS_BODYNODE_IDX = 2
RIGHT_BODYNODE_IDX = 5
LEFT_BODYNODE_IDX = 8

# Same as 2D model, except L_PELVIS
L_PELVIS = 0.15
L_THIGH =    0.45
L_SHIN =   0.50
L_FOOT =   0.20
FOOT_RADIUS = 0.06

KP_GAIN = 300.0
KD_GAIN = 20.0

ALLOWED_COLLISION_IDS = [5,8] # The two feet
