# All models

IK_GAIN = 0
POSITION_BALANCE_GAIN = 1
VELOCITY_BALANCE_GAIN = 2
TORSO_WORLD = 3
STANCE_ANKLE_RELATIVE = 4

UP_IDX = 5
DN_IDX = 9
# These 4 params are different depending on whether we're going "up" or "down"
SWING_HIP_WORLD = 0
SWING_KNEE_RELATIVE = 1
SWING_ANKLE_RELATIVE = 2
STANCE_KNEE_RELATIVE = 3

TX = 13
TY = 14
TZ = 15

# 3D models

POSITION_BALANCE_GAIN_LAT = 16
VELOCITY_BALANCE_GAIN_LAT = 17
YAW_WORLD = 18
STANCE_HIP_ROLL_EXTRA = 19
STANCE_ANKLE_ROLL = 20
